# Use the official Node.js image
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN yarn install

# Copy the rest of the application code
COPY . .

# Pass environment variables as build arguments
ARG DATABASE_URL
ARG JWT_SECRET
ARG UPLOADTHING_SECRET
ARG UPLOADTHING_APP_ID
ARG UPLOADTHING_TOKEN
ARG RESEND_API_KEY
ARG NEXT_PUBLIC_APP_URL

# Set environment variables
ENV DATABASE_URL=$DATABASE_URL
ENV JWT_SECRET=$JWT_SECRET
ENV UPLOADTHING_SECRET=$UPLOADTHING_SECRET
ENV UPLOADTHING_APP_ID=$UPLOADTHING_APP_ID
ENV UPLOADTHING_TOKEN=$UPLOADTHING_TOKEN
ENV RESEND_API_KEY=$RESEND_API_KEY
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NODE_ENV=production

# Build the application
RUN yarn build

# Production image, copy all the files and run next
FROM node:18-alpine AS runner

WORKDIR /app

# Don't run production as root
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

# Set environment variables for runtime
ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000

CMD ["node", "server.js"]